# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754fbe48f744c5bed7a5248be2ccbde60a35334793f284e27454ab19eac0ea37c6b04c27dfa4b3787af18642ad53ef2814e27a9d830175394cd0f8f8fa65d02e

test:
  secret_key_base: 9cd466535e90027c47f73975020f34a40c98fb59962b2162773207d48de81ce27ebdb97934923c1af3d524513e363d93304a28d6b450586c0cdb21963ce4c7a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
